name: flutter_jailbreak_detection
description: Flutter jailbreak and root detection plugin
version: 1.0.0
author: Jeroen Trappers <jeroen@appmire.be>
homepage: https://github.com/jeroentrappers/flutter_jailbreak_detection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: appmire.be.flutterjailbreakdetection
    pluginClass: FlutterJailbreakDetectionPlugin