name: flutter_jailbreak_detection
description: Flutter jailbreak and root detection plugin
version: 1.2.0
homepage: https://github.com/jeroentrappers/flutter_jailbreak_detection

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: appmire.be.flutterjailbreakdetection
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: FlutterJailbreakDetectionPlugin
